language: node_js
node_js: "node"
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
cache:
  directories:
    - node_modules
before_install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
install:
  - npm install
script:
  - npm run lint:package
  - npm run lint:readme
  - npm run lint:editorconfig
  - npm run lint:man
  - shellcheck git-open
  - npm run man
  - ./bats/bin/bats test/*.bats
